version: '3.8'

services:
  db:
    container_name: doq_project_db
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"

  web:
    container_name: doq_project_web
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - STATIC_URL=${STATIC_URL}
      - STATIC_ROOT=${STATIC_ROOT}
      - MEDIA_URL=${MEDIA_URL}
      - MEDIA_ROOT=${MEDIA_ROOT}
      - INTERNAL_IPS=46.101.243.200
      - TEMPLATES_DIRS=${TEMPLATES_DIRS}
    depends_on:
      - db
      - esearch

  esearch:
    container_name: esearch
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - web
    ports:
      - 81:8000
      - 443:443
    volumes:
      - static-data:/vol/static
volumes:
  pg_data:
  static-data:

