version: '3.8'

services:
  db:
    container_name: doq_project_db
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: postgres
      POSTGRES_DB: doq_project_local_docker_db
    ports:
      - "5432:5432"
  web:
    container_name: doq_project_web
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py collectstatic --no-input &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    restart: always
    volumes:
      - .:/usr/src/doq_project
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: doq_project_local_docker_db

    depends_on:
      - db
      - esearch
  esearch:
    container_name: esearch
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./logs/:/logs
      - static:/static
      - media:/media
    ports:
      - "1221:80"
    links:
      - web
volumes:
  pg_data:
  media:
  static: