version: '3.8'

services:
  db:
    container_name: doq_project_db
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"

  web:
    container_name: doq_project_web
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
      - esearch

  esearch:
    container_name: esearch
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - web
    ports:
      - 80:8000
      - 443:443
    volumes:
      - static-data:/vol/static
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    depends_on:
      - proxy
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email daurenotarbai.00@gmail.com --agree-tos --no-eff-email -d onmenu.site

volumes:
  www-html:
  pg_data:
  static-data:
  etc-letsencrypt:
