# Generated by Django 4.0.5 on 2022-07-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('name_clinic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название клиники')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя клиента')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterField(
            model_name='schedules',
            name='end_day',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start_day',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
