# Generated by Django 4.0.5 on 2022-08-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinicapplication_alter_schedules_end_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='doctor',
            name='operates_from',
            field=models.DateField(auto_now=True, verbose_name='Работает с'),
        ),
    ]
