# Generated by Django 4.0.5 on 2022-08-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_doctor_achievements_doctor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='short_description',
            field=models.CharField(default='', max_length=120, verbose_name='Краткое описание'),
        ),
    ]
