# Generated by Django 4.0.5 on 2022-06-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_doctor_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
    ]
