# Generated by Django 4.0.5 on 2022-07-26 12:27

import apps.clinics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_clinic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='for_child',
            field=models.BooleanField(blank=True, default=True, verbose_name='Детский'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.clinics.models.clinic_photo_path, verbose_name='Файл с изображением'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.clinics.models.clinic_photo_path, verbose_name='Лого клиники'),
        ),
    ]
