# Generated by Django 4.0.5 on 2022-08-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_short_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentdoctortime',
            unique_together={('doctor', 'date', 'clinic_address')},
        ),
    ]
