# Generated by Django 4.0.5 on 2022-06-25 04:13

import apps.clinics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_doctor_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.clinics.models.clinic_photo_path, verbose_name='Файл с изображением'),
        ),
        migrations.DeleteModel(
            name='ClinicPhoto',
        ),
    ]
