# Generated by Django 4.0.5 on 2022-08-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_remove_doctor_experience_years_doctor_operates_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='operates_from',
            field=models.DateField(verbose_name='Работает с'),
        ),
    ]
