# Generated by Django 4.0.5 on 2022-08-27 08:10

import apps.clinics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_clinicapplication_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicapplication',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.clinics.models.doctor_application_photo_path, verbose_name='Фото доктора'),
        ),
    ]
