# Generated by Django 4.0.5 on 2022-07-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_schedules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedules',
            unique_together={('day_in_week', 'address')},
        ),
    ]
