# Generated by Django 4.0.5 on 2022-07-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_alter_schedules_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_24_hours',
            field=models.BooleanField(blank=True, default=False, verbose_name='Круглосуточно'),
        ),
    ]
