# Generated by Django 4.0.5 on 2022-08-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_alter_doctorprocedures_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.CharField(default='', max_length=25),
        ),
    ]
