# Generated by Django 4.0.5 on 2022-08-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_doctorprocedures_new_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Названия категории')),
            ],
            options={
                'verbose_name': 'Категория доктора',
                'verbose_name_plural': 'Категории доктора',
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='category',
        ),
        migrations.AddField(
            model_name='doctor',
            name='categories',
            field=models.ManyToManyField(blank=True, to='clinics.doctorcategory', verbose_name='Категории доктора'),
        ),
    ]
