# Generated by Django 4.0.5 on 2022-08-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.CharField(max_length=25),
        ),
    ]
