# Generated by Django 4.0.5 on 2022-08-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_doctorcategory_remove_doctor_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprocedures',
            name='child_age_from',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprocedures',
            name='child_age_to',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorspecialities',
            name='child_age_from',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorspecialities',
            name='child_age_to',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
