# Generated by Django 4.0.5 on 2022-08-29 19:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_doctorprocedures_child_age_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='discount_consultation_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка на стоимость приема'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorprocedures',
            name='child_age_from',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='doctorprocedures',
            name='child_age_to',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='doctorspecialities',
            name='child_age_from',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='doctorspecialities',
            name='child_age_to',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)]),
        ),
    ]
