# Generated by Django 4.0.5 on 2022-08-29 19:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_doctor_discount_consultation_fee_doctor_new_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprocedures',
            name='child_age_from',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)], verbose_name='Возраст детей от'),
        ),
        migrations.AlterField(
            model_name='doctorprocedures',
            name='child_age_to',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)], verbose_name='Возраст детей до'),
        ),
        migrations.AlterField(
            model_name='doctorprocedures',
            name='child_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка (Детский)'),
        ),
        migrations.AlterField(
            model_name='doctorprocedures',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Цена приема (Детский)'),
        ),
        migrations.AlterField(
            model_name='doctorprocedures',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='doctorprocedures',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_procedures', to='clinics.doctor', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='doctorprocedures',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Цена приема'),
        ),
        migrations.AlterField(
            model_name='doctorprocedures',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_procedures', to='clinics.procedure', verbose_name='Процедура'),
        ),
        migrations.AlterField(
            model_name='doctorspecialities',
            name='child_age_from',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)], verbose_name='Возраст детей от'),
        ),
        migrations.AlterField(
            model_name='doctorspecialities',
            name='child_age_to',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)], verbose_name='Возраст детей до'),
        ),
        migrations.AlterField(
            model_name='doctorspecialities',
            name='child_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка (Детский)'),
        ),
        migrations.AlterField(
            model_name='doctorspecialities',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Цена приема (Детский)'),
        ),
        migrations.AlterField(
            model_name='doctorspecialities',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='doctorspecialities',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialities', to='clinics.doctor', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='doctorspecialities',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Цена приема'),
        ),
        migrations.AlterField(
            model_name='doctorspecialities',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialities', to='clinics.speciality', verbose_name='Специальность'),
        ),
    ]
