# Generated by Django 4.0.5 on 2022-08-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
