# Generated by Django 4.0.5 on 2022-08-17 15:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialities',
            field=models.ManyToManyField(related_name='doctors', through='clinics.DoctorSpecialities', to='clinics.speciality', verbose_name='Специальности'),
        ),
        migrations.AddField(
            model_name='doctorspecialities',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialities', to='clinics.doctor'),
        ),
        migrations.AddField(
            model_name='doctorspecialities',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialities', to='clinics.speciality'),
        ),
    ]
