# Generated by Django 4.0.5 on 2022-09-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_remove_address_city_clinic_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprocedures',
            options={'verbose_name': 'Процедура доктора', 'verbose_name_plural': 'Процедуры доктора'},
        ),
        migrations.AlterModelOptions(
            name='doctorspecialities',
            options={'verbose_name': 'Специальность доктора', 'verbose_name_plural': 'Специальности доктора'},
        ),
        migrations.AddField(
            model_name='doctorprocedures',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.address'),
        ),
        migrations.AddField(
            model_name='doctorprocedures',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='doctorspecialities',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.address'),
        ),
        migrations.AddField(
            model_name='doctorspecialities',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активный'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorprocedures',
            unique_together={('doctor', 'procedure', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='doctorspecialities',
            unique_together={('doctor', 'speciality', 'address')},
        ),
    ]
