# Generated by Django 4.0.5 on 2022-08-19 13:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_doctorspecialities_alter_doctor_specialities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprocedures',
            name='child_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprocedures',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorprocedures',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprocedures',
            name='for_child',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Детский'),
        ),
        migrations.AddField(
            model_name='doctorspecialities',
            name='child_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorspecialities',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorspecialities',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorspecialities',
            name='for_child',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Детский'),
        ),
    ]
