# Generated by Django 4.0.5 on 2022-09-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_alter_doctorprocedures_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorClinicAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, choices=[('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('40', '40'), ('45', '45'), ('50', '50'), ('60', '60'), ('90', '90')], default='30', max_length=10, verbose_name='Пол')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_address', to='clinics.address', verbose_name='Адрес')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_address', to='clinics.doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Адрес доктора',
                'verbose_name_plural': 'Адрес доктора',
                'unique_together': {('doctor', 'address')},
            },
        ),
    ]
