# Generated by Django 4.0.5 on 2022-09-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0015_doctorclinicaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='code',
            field=models.CharField(choices=[('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('40', '40'), ('45', '45'), ('50', '50'), ('60', '60'), ('90', '90')], default='30', max_length=30),
        ),
    ]
