# Generated by Django 4.0.5 on 2022-09-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0017_alter_appointmenttime_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['is_top', '?'], 'verbose_name': 'Доктор', 'verbose_name_plural': 'Докторы'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_top',
            field=models.BooleanField(blank=True, default=False, verbose_name='Топ'),
        ),
    ]
