# Generated by Django 4.0.5 on 2022-09-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0018_alter_doctor_options_doctor_is_top'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-is_top', '?'], 'verbose_name': 'Доктор', 'verbose_name_plural': 'Докторы'},
        ),
    ]
