# Generated by Django 4.0.5 on 2022-09-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0020_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprocedures',
            name='for_child',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Детский'),
        ),
        migrations.AlterField(
            model_name='doctorspecialities',
            name='for_child',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Детский'),
        ),
    ]
