# Generated by Django 4.0.5 on 2022-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_responded',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ответил'),
        ),
    ]
