# Generated by Django 4.0.5 on 2022-07-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='iin',
            field=models.CharField(blank=True, default='', max_length=12, unique=True, verbose_name='ЖСН'),
        ),
    ]
