# Generated by Django 4.0.5 on 2022-08-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_alter_doctorprocedures_child_age_from_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinics.doctorprocedures'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinics.doctorspecialities'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_child',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
