# Generated by Django 4.0.5 on 2022-09-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointment_doctor_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примичание'),
        ),
    ]
