# Generated by Django 4.0.5 on 2022-08-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_comment_is_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_visited',
            field=models.BooleanField(blank=True, null=True, verbose_name='Посетил'),
        ),
    ]
