# Generated by Django 4.0.5 on 2022-07-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinic_image_delete_clinicphoto'),
        ('patients', '0004_alter_appointment_appointment_doctor_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('appointment_time', 'appointment_doctor_time')},
        ),
    ]
