# Generated by Django 4.0.5 on 2022-08-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_doctorprocedures_child_discount_and_more'),
        ('patients', '0005_alter_comment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clinics.doctor'),
        ),
    ]
